version: '3.8'

services:
  app:
    container_name: snapgo
    build: .
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - mongo
    networks:
      - fullstack


  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./data:/data
    ports:
      - 27017:27017

volumes:
  app:

networks:
  fullstack:
